services:
  vohive:
    build:
      context: .
      dockerfile: Dockerfile
    image: zhangsan-nb/vohive:v1.5.5-10-gf9eb85d
    container_name: vohive
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - /dev:/dev
    environment:
      TZ: Asia/Shanghai
